//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSULTA
    {
        public int cons_id { get; set; }
        public string cons_turno { get; set; }
        public string cons_situacao { get; set; }
        public System.DateTime cons_dataConsulta { get; set; }
        public int pac_id { get; set; }
        public int med_id { get; set; }
        public int conv_id { get; set; }
    
        public virtual CONVENIO CONVENIO { get; set; }
        public virtual MEDICO MEDICO { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
    }
}
