//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEDICO()
        {
            this.CONSULTA = new HashSet<CONSULTA>();
        }
    
        public int med_id { get; set; }
        public string med_nom { get; set; }
        public string med_end { get; set; }
        public string med_cpf { get; set; }
        public Nullable<int> med_fone { get; set; }
        public string med_crm { get; set; }
        public string med_cidade { get; set; }
        public string med_estado { get; set; }
        public int med_qtd_atend { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSULTA> CONSULTA { get; set; }
    }
}
